# 02-异常处理结构


## try ... 一个 except结构


try...except 是最常见的异常处理结构。结构如下：

```
try:
    被监控可能引发异常的语句快
except BaseException [as e]:
    异常处理语句块

```

try块包含着可能引发异常的代码，except块则用来捕捉和处理发生的异常。执行的时候，如果try块中没有引发异常，则跳过except块执行后续代码；执行的时候，如果try块发生了异常，则跳过try块中的后续代码，跳到相应的except块中处理异常；异常处理完后，继续执行后续代码。


案例：
```
# 测试简单的0不能做除数异常

try:
    print("step1")
    a = 3 / 0
    print("step2")

except BaseException as e:
    print("step3")
    print(e)

print("step4")
```

执行结果如下：
step1
step3
division by zero
step4


案例：
```
# 循环输入数字，如果不是数字则处理异常，直到输入88，则结束循环

while True:
    try:
        x = int(input("请输入一个整数"))
        print("输入的数字: ", x)
        if x == 88:
            print("程序结束")
            break
    except BaseException as e:
        print("输入的不是一个数字")
        print(e)

print("循环数字输入程序结束")
```

执行结果如下：
```
请输入一个整数add
输入的不是一个数字
invalid literal for int() with base 10: 'add'
请输入一个整数90
输入的数字:  90
请输入一个整数88
输入的数字:  88
程序结束
循环数字输入程序结束

```


## try...多个except结构


上面的结构可以捕获所有的异常，工作中也很常见。但是，从经典理论考虑，一般建议尽量捕获可能出现的多个异常（按照先子类后父类的顺序），并且针对性的写出异常处理代码。为了避免遗漏可能出现的异常，可以在最后增加BaseException。结构如下：

```
try:
    被监控的、可能引发异常的语句块
exception Exception1:
    处理Exception1的语句块
exception Exception2:
    处理Exception2的语句块

...
excepetion BaseException：
    处理可能遗漏的异常的语句块
```

案例：

```
# 测试多个try...except结构

try:
    a = input("请输入一个被除数：")
    b = input("请输入一个除数：")
    c = float(a) / float(b)
    print(c)
except ZeroDivisionError:
    print("异常，除数不能是0")
except ValueError:
    print("异常，不能将字符串转为数字")
except NameError:
    print("变量不存在")
except BaseException as e:
    print(e)

```


## else结构

try...except...else结构增加了else块。如果try块中没有抛出异常，则执行else块。如果try块中抛出异常，则执行except块，不执行else块。


案例：try...except...else结构执行测试


```
# 测试try...except...else结构
try:
    a = input("请输入被除数：")
    b = input("请输入除数：")
    c = float(a) / float(b)
except BaseException as e:
    print(e)
else:
    print("除数的结果是：", c)
```

执行结果：
```
不抛异常执行结果,没有执行else语句块：
请输入被除数：90
请输入除数：9
除数的结果是： 10.0

抛异常结果，执行else语句块：
请输入被除数：ddd
请输入除数：20
could not convert string to float: 'ddd'
```



## finally结构


try...except...finally结构中，finally块无论是否发生异常都会执行；通常用来释放try块中申请的资源。


案例：
```
# 测试try...except...finally 结构


try:
    a = input("请输入一个被除数：")
    b = input("请输入一个除数：")
    c = float(a) / float(b)

except BaseException as e:
    print(e)

else:
    print(c)

finally:
    print("我是finally的语句，无论是否发生异常，都会执行！")

print("程序结束")
```

执行结果如下：
 ```
请输入一个被除数：90
请输入一个除数：10
9.0
我是finally的语句，无论是否发生异常，都会执行！
程序结束
 ```

**建议：**

一般不要将return语句放到try、except、else、finally块中，会发生一些意想不到的错误。建议放到方法最后。